# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_path = os.path.join('..', 'output_data', 'cities.csv')

csv_read = pd.read_csv(csv_path)
csv_read.head()

,ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,6185377,Yellowknife,62.4560,-114.3525,-1.42,51,75,4.12,CA,2021-04-30 01:54:21
1,5364271,Laguna,38.4210,-121.4238,30.30,16,1,3.09,US,2021-04-30 01:52:45
2,4030556,Rikitea,-23.1203,-134.9692,25.03,63,77,5.74,PF,2021-04-30 01:54:18
3,3369157,Cape Town,-33.9258,18.4232,12.96,93,0,2.57,ZA,2021-04-30 01:50:17
4,933649,Khakhea,-24.6895,23.4940,16.76,82,62,3.66,BW,2021-04-30 02:04:12

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [10]:
Lat_Long = csv_read[["Lat", "Lng"]]
humidity = csv_read["Humidity"]

fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(Lat_Long, weights=humidity, dissipating=False)
heat_layer.max_intensity = 100
heat_layer.point_radius = 5


fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# I adjusted the data quite a bit

new_df = csv_read[(csv_read['Max Temp'] <= 50) & (csv_read['Max Temp'] >= 25)] 
new_df = new_df[new_df['Wind Speed'] <= 10]
new_df = new_df[new_df['Cloudiness'] <= 25]

new_df.head()

,ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
1,5364271,Laguna,38.4210,-121.4238,30.30,16,1,3.09,US,2021-04-30 01:52:45
6,2068110,Kununurra,-15.7667,128.7333,32.00,29,0,4.63,AU,2021-04-30 01:59:20
28,1151464,Phang Nga,8.4509,98.5298,28.26,83,20,2.57,TH,2021-04-30 02:04:20
45,2063042,Port Hedland,-20.3167,118.5667,34.00,20,0,2.57,AU,2021-04-30 01:54:41
46,1783873,Zhumadian,32.9794,114.0294,25.21,49,0,6.44,CN,2021-04-30 02:04:25

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = new_df

hotel_df['Hotel Name'] = ' '
hotel_df

,ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
1,5364271,Laguna,38.4210,-121.4238,30.30,16,1,3.09,US,2021-04-30 01:52:45,
6,2068110,Kununurra,-15.7667,128.7333,32.00,29,0,4.63,AU,2021-04-30 01:59:20,
28,1151464,Phang Nga,8.4509,98.5298,28.26,83,20,2.57,TH,2021-04-30 02:04:20,
45,2063042,Port Hedland,-20.3167,118.5667,34.00,20,0,2.57,AU,2021-04-30 01:54:41,
46,1783873,Zhumadian,32.9794,114.0294,25.21,49,0,6.44,CN,2021-04-30 02:04:25,
55,1258338,Ratnagiri,16.9833,73.3000,28.64,71,16,1.67,IN,2021-04-30 02:04:29,
75,1270961,Gopālpur,19.2667,84.9167,28.63,74,0,6.16,IN,2021-04-30 02:04:36,
76,1735106,George Town,5.4112,100.3354,28.04,83,20,2.06,MY,2021-04-30 01:54:10,
101,1252948,Warangal,18.0000,79.5833,28.84,54,4,5.90,IN,2021-04-30 02:04:45,
138,4020109,Atuona,-9.8000,-139.0333,26.30,69,13,1.98,PF,2021-04-30 02:04:59,
147,100926,Umluj,25.0213,37.2685,29.18,40,6,3.92,SA,2021-04-30 02:05:02,
190,3373652,Oistins,13.0667,-59.5333,25.00,61,20,4.63,BB,2021-04-30 02:05:19,
195,4004293,Ixtapa,20.7000,-105.2000,25.78,73,1,4.12,MX,2021-04-30 01:57:28,
231,1626703,Soe,-9.8607,124.2840,25.85,62,17,3.26,ID,2021-04-30 01:55:49,
234,3991622,La Providencia,28.7167,-111.5833,29.38,26,1,4.02,MX,2021-04-30 02:05:35,
235,1268610,Athmallik,20.7219,84.5348,30.49,43,0,1.95,IN,2021-04-30 02:05:35,
242,2439155,Tanout,14.9709,8.8879,25.71,7,2,2.87,NE,2021-04-30 02:05:38,
286,3374083,Bathsheba,13.2167,-59.5167,25.00,61,20,4.63,BB,2021-04-30 02:05:54,
294,3557923,Guáimaro,21.0500,-77.3500,25.00,78,1,4.12,CU,2021-04-30 02:05:58,
306,4169130,Port Charlotte,26.9762,-82.0906,25.39,78,1,2.06,US,2021-04-30 02:06:03,
312,4705349,Laredo,27.5064,-99.5075,26.91,53,1,7.20,US,2021-04-30 02:02:17,
313,64814,Bandarbeyla,9.4942,50.8122,27.76,77,22,1.72,SO,2021-04-30 02:06:05,
343,290030,Doha,25.2867,51.5333,25.32,38,0,2.57,QA,2021-04-30 02:06:16,
348,3563856,Colombia,20.9881,-77.4297,25.00,78,1,4.12,CU,2021-04-30 02:06:18,
352,1270287,Harpanahalli,14.8000,75.9833,26.92,45,11,0.85,IN,2021-04-30 02:06:20,
357,1645528,Denpasar,-8.6500,115.2167,29.00,79,20,4.12,ID,2021-04-30 02:03:50,
366,3615683,Wiwilí,13.6268,-85.8254,25.19,44,6,1.91,NI,2021-04-30 02:06:25,
374,1276728,Bāsugaon,26.4667,90.4000,32.29,26,0,0.88,IN,2021-04-30 02:06:28,
378,1861416,Ishigaki,24.3448,124.1572,25.00,65,20,2.57,JP,2021-04-30 02:06:30,
388,3520064,Salina Cruz,16.1667,-95.2000,27.85,76,6,5.89,MX,2021-04-30 02:06:34,
392,3616594,San Rafael del Sur,11.8485,-86.4384,31.00,51,20,3.09,NI,2021-04-30 02:06:35,
397,1714733,Dingle,10.9995,122.6711,31.17,42,18,2.57,PH,2021-04-30 02:06:37,
404,1650213,Banjarmasin,-3.3244,114.5910,29.00,79,0,3.60,ID,2021-04-30 01:59:30,
410,5546220,Saint George,37.1041,-113.5841,28.44,13,1,5.66,US,2021-04-30 02:02:13,
424,2210554,Sirte,31.2089,16.5887,27.07,27,4,4.11,LY,2021-04-30 02:06:47,
438,1174451,Keti Bandar,24.1447,67.4497,27.51,78,5,4.51,PK,2021-04-30 02:06:52,
440,4161957,Lighthouse PT,26.2756,-80.0873,26.19,73,1,3.09,US,2021-04-30 02:06:53,
441,223816,Djibouti,11.5000,42.5000,29.00,74,1,5.14,DJ,2021-04-30 02:06:53,
465,1806041,Jiaocheng,24.6774,116.1389,26.53,44,9,1.22,CN,2021-04-30 02:07:04,
468,1583992,Turan,16.0678,108.2208,30.00,58,20,1.54,VN,2021-04-30 02:02:57,
477,2392087,Porto-Novo,6.4965,2.6036,28.00,83,20,2.57,BJ,2021-04-30 02:06:21,
487,1337610,Thinadhoo,0.5333,72.9333,28.44,71,21,1.98,MV,2021-04-30 02:07:12,
509,5505411,Henderson,36.0397,-114.9819,29.74,10,1,3.09,US,2021-04-30 02:04:48,
521,95788,Hīt,33.6416,42.8251,25.77,24,0,5.47,IQ,2021-04-30 02:07:24,
525,2440371,Ouallam,14.3188,2.0866,30.59,22,5,1.53,NE,2021-04-30 02:07:26,
533,2065594,Mount Isa,-20.7333,139.5000,29.00,34,1,3.60,AU,2021-04-30 02:07:29,
550,1650232,Banjar,-8.1900,114.9675,29.00,79,20,4.12,ID,2021-04-30 02:07:36,

In [7]:
for index, row in hotel_df.iterrows():
    try:
        url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
        params = {'keyword': 'hotel', 'radius': 5000, 'key': g_key}
        lat = row['Lat']
        lng = row['Lng']
        params['location'] = f'{lat}, {lng}'
        hotel_data = requests.get(url, params=params).json()
        hotel_df.loc[index, 'Hotel Name'] = hotel_data['results'][0]['name']
        
    except IndexError:
        
        hotel_df.loc[index, "Hotel Name"] = 'No result'
        
hotel_df

,ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
1,5364271,Laguna,38.4210,-121.4238,30.30,16,1,3.09,US,2021-04-30 01:52:45,Hampton Inn & Suites Sacramento-Elk Grove Lagu...
6,2068110,Kununurra,-15.7667,128.7333,32.00,29,0,4.63,AU,2021-04-30 01:59:20,Freshwater East Kimberley Apartments | Kununur...
28,1151464,Phang Nga,8.4509,98.5298,28.26,83,20,2.57,TH,2021-04-30 02:04:20,Blue Mountain Phangnga Resort and Restaurant
45,2063042,Port Hedland,-20.3167,118.5667,34.00,20,0,2.57,AU,2021-04-30 01:54:41,Hedland Hotel
46,1783873,Zhumadian,32.9794,114.0294,25.21,49,0,6.44,CN,2021-04-30 02:04:25,IKE INTERNATIONAL HOTEL
55,1258338,Ratnagiri,16.9833,73.3000,28.64,71,16,1.67,IN,2021-04-30 02:04:29,"Kohinoor Samudra Beach Resort, Ratnagiri"
75,1270961,Gopālpur,19.2667,84.9167,28.63,74,0,6.16,IN,2021-04-30 02:04:36,"MAYFAIR Palm Beach Resort, Gopalpur"
76,1735106,George Town,5.4112,100.3354,28.04,83,20,2.06,MY,2021-04-30 01:54:10,"Eastern & Oriental Hotel, Penang"
101,1252948,Warangal,18.0000,79.5833,28.84,54,4,5.90,IN,2021-04-30 02:04:45,Sharanya Hotel
138,4020109,Atuona,-9.8000,-139.0333,26.30,69,13,1.98,PF,2021-04-30 02:04:59,Hôtel Hiva Oa Hanakee Lodge
147,100926,Umluj,25.0213,37.2685,29.18,40,6,3.92,SA,2021-04-30 02:05:02,HP Red Sea Hotel
190,3373652,Oistins,13.0667,-59.5333,25.00,61,20,4.63,BB,2021-04-30 02:05:19,South Gap Hotel
195,4004293,Ixtapa,20.7000,-105.2000,25.78,73,1,4.12,MX,2021-04-30 01:57:28,Flamingo Vallarta Hotel & Marina
231,1626703,Soe,-9.8607,124.2840,25.85,62,17,3.26,ID,2021-04-30 01:55:49,Dena Hotel
234,3991622,La Providencia,28.7167,-111.5833,29.38,26,1,4.02,MX,2021-04-30 02:05:35,No result
235,1268610,Athmallik,20.7219,84.5348,30.49,43,0,1.95,IN,2021-04-30 02:05:35,Hotel Shree Jagannath Athmallik
242,2439155,Tanout,14.9709,8.8879,25.71,7,2,2.87,NE,2021-04-30 02:05:38,No result
286,3374083,Bathsheba,13.2167,-59.5167,25.00,61,20,4.63,BB,2021-04-30 02:05:54,Atlantis Hotel
294,3557923,Guáimaro,21.0500,-77.3500,25.00,78,1,4.12,CU,2021-04-30 02:05:58,Hotel Guáimaro
306,4169130,Port Charlotte,26.9762,-82.0906,25.39,78,1,2.06,US,2021-04-30 02:06:03,Four Points by Sheraton Punta Gorda Harborside
312,4705349,Laredo,27.5064,-99.5075,26.91,53,1,7.20,US,2021-04-30 02:02:17,Gran Hotel Cantera
313,64814,Bandarbeyla,9.4942,50.8122,27.76,77,22,1.72,SO,2021-04-30 02:06:05,Super secret pirate cove
343,290030,Doha,25.2867,51.5333,25.32,38,0,2.57,QA,2021-04-30 02:06:16,The Curve Hotel
348,3563856,Colombia,20.9881,-77.4297,25.00,78,1,4.12,CU,2021-04-30 02:06:18,No result
352,1270287,Harpanahalli,14.8000,75.9833,26.92,45,11,0.85,IN,2021-04-30 02:06:20,Capital O 68835 Samatha Resort
357,1645528,Denpasar,-8.6500,115.2167,29.00,79,20,4.12,ID,2021-04-30 02:03:50,Segara Village Hotel
366,3615683,Wiwilí,13.6268,-85.8254,25.19,44,6,1.91,NI,2021-04-30 02:06:25,Hotel Victoria
374,1276728,Bāsugaon,26.4667,90.4000,32.29,26,0,0.88,IN,2021-04-30 02:06:28,No result
378,1861416,Ishigaki,24.3448,124.1572,25.00,65,20,2.57,JP,2021-04-30 02:06:30,Beach Hotel Sunshine
388,3520064,Salina Cruz,16.1667,-95.2000,27.85,76,6,5.89,MX,2021-04-30 02:06:34,Hotel y Suites Del Paci­fico
392,3616594,San Rafael del Sur,11.8485,-86.4384,31.00,51,20,3.09,NI,2021-04-30 02:06:35,No result
397,1714733,Dingle,10.9995,122.6711,31.17,42,18,2.57,PH,2021-04-30 02:06:37,No result
404,1650213,Banjarmasin,-3.3244,114.5910,29.00,79,0,3.60,ID,2021-04-30 01:59:30,Mercure Banjarmasin
410,5546220,Saint George,37.1041,-113.5841,28.44,13,1,5.66,US,2021-04-30 02:02:13,Comfort Inn Saint George North
424,2210554,Sirte,31.2089,16.5887,27.07,27,4,4.11,LY,2021-04-30 02:06:47,No result
438,1174451,Keti Bandar,24.1447,67.4497,27.51,78,5,4.51,PK,2021-04-30 02:06:52,No result
440,4161957,Lighthouse PT,26.2756,-80.0873,26.19,73,1,3.09,US,2021-04-30 02:06:53,Wyndham Deerfield Beach Resort
441,223816,Djibouti,11.5000,42.5000,29.00,74,1,5.14,DJ,2021-04-30 02:06:53,No result
465,1806041,Jiaocheng,24.6774,116.1389,26.53,44,9,1.22,CN,2021-04-30 02:07:04,No result
468,1583992,Turan,16.0678,108.2208,30.00,58,20,1.54,VN,2021-04-30 02:02:57,Pullman Danang Beach Resort
477,2392087,Porto-Novo,6.4965,2.6036,28.00,83,20,2.57,BJ,2021-04-30 02:06:21,Rédidence OUADADA
487,1337610,Thinadhoo,0.5333,72.9333,28.44,71,21,1.98,MV,2021-04-30 02:07:12,No result
509,5505411,Henderson,36.0397,-114.9819,29.74,10,1,3.09,US,2021-04-30 02:04:48,Comfort Inn & Suites Henderson - Las Vegas
521,95788,Hīt,33.6416,42.8251,25.77,24,0,5.47,IQ,2021-04-30 02:07:24,No result
525,2440371,Ouallam,14.3188,2.0866,30.59,22,5,1.53,NE,2021-04-30 02:07:26,No result
533,2065594,Mount Isa,-20.7333,139.5000,29.00,34,1,3.60,AU,2021-04-30 02:07:29,Redearth Boutique Hotel
550,1650232,Banjar,-8.1900,114.9675,29.00,79,20,4.12,ID,2021-04-30 02:07:36,Padmasari Resort Hotel

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [9]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
fig

# Display figure

Figure(layout=FigureLayout(height='420px'))